project:
  type: website

website:
  site-url: https://computing.stat.berkeley.edu/tutorial-dask-future
  sidebar:
    style: docked
    title: "SCF Dask and Future Tutorial"
    logo: assets/img/logo.svg
    logo-href: https://statistics.berkeley.edu
    logo-alt: "UC Berkeley Statistics logo"
    tools:
      - icon: github
        href: https://github.com/berkeley-scf/tutorial-dask-future
        aria-label: GitHub
    contents:
      - href: index.qmd
        text: Overview
      - href: python-dask.qmd
        text: Dask in Python
      - href: python-ray.qmd
        text: Ray in Python
      - href: R-future.qmd
        text: future in R
      - href: license.qmd
        text: License

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
